#! /bin/sh
# interlock - wrap program invocation in lock to allow
#             parallel builds to work.
# Written by Tom Tromey <tromey@cygnus.com>, Aug 10 1996
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# Pick a filename.  Hopefully no-one actually uses this name.
dirname='=interlockdir'

while (mkdir $dirname > /dev/null 2>&1 && exit 1 || exit 0); do
   # Nothing.
   :
done

# We have the lock.
prog="$1"
progoutput="$2"
realoutput="$3"
shift
shift
shift

$prog ${1+"$@"}
ret=$?

if test -f "$progoutput"; then
   mv "$progoutput" "$realoutput" || ret=$?
fi

# Release the lock.
rmdir $dirname > /dev/null 2>&1

exit $ret
