#! /bin/sh
# ylwrap - wrapper for lex/yacc invocations.
# Written by Tom Tromey <tromey@cygnus.com>, Aug 11 1996
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# The program to run.
prog="$1"

# The output file the program generates, eg `y.tab.c'.
progoutput="$2"

# The output file we actually want.
realoutput="$3"

# Strip arguments we've used; remaining arguments go to PROG.
shift
shift
shift

$prog ${1+"$@"} || exit $?

if test -f "$progoutput"; then
   mv "$progoutput" "$realoutput" || exit $?
else
   exit 1
fi
exit 0
