## Makefile fragment that holds the list of test scripts of the automake
## testsuite.  This fragment is meant to be included by the Makefile.am,
## but also to be executed directly by make when bootstrapping automake.

## Copyright (C) 2011-2012 Free Software Foundation, Inc.
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2, or (at your option)
## any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

# FIXME: this "expected failures" are in truth an hack used to
# FIXME: to verify that some incorrect usages of our perl libraries
# FIXME: raise an error.  We should find a cleaner way to check that.
perl_fake_XFAIL_TESTS = \
pm/Cond2.pl \
pm/Cond3.pl \
pm/DisjCon2.pl \
pm/DisjCon3.pl \
pm/Version2.pl \
pm/Version3.pl

XFAIL_TESTS = \
all.sh \
yacc-bison-skeleton-cxx.sh \
yacc-bison-skeleton.sh \
cond17.sh \
gcj6.sh \
override-conditional-2.sh \
dist-pr109765.sh \
instdir-cond2.sh \
java-nobase.sh \
objext-pr10128.sh \
parallel-tests-many.sh \
pr8365-remake-timing.sh \
lex-subobj-nodep.sh \
remake-am-pr10111.sh \
remake-m4-pr10111.sh \
txinfo5.sh \
$(perl_fake_XFAIL_TESTS)

perl_TESTS = \
pm/Cond2.pl \
pm/Cond3.pl \
pm/Condition.pl \
pm/Condition-t.pl \
pm/DisjCon2.pl \
pm/DisjCon3.pl \
pm/DisjConditions.pl \
pm/DisjConditions-t.pl \
pm/Version.pl \
pm/Version2.pl \
pm/Version3.pl \
pm/Wrap.pl

# The order here is mostly alphabetical, with the deliberate exception
# that tests having a high runtime (especially TAP tests that run various
# checks sequentially) are listed early; this improves performance on
# concurrent testsuite runs.
handwritten_TESTS = \
get-sysconf.sh \
$(perl_TESTS) \
instspc.tap \
aclocal.sh \
aclocal3.sh \
aclocal4.sh \
aclocal5.sh \
aclocal6.sh \
aclocal7.sh \
aclocal8.sh \
aclocal9.sh \
acloca10.sh \
acloca11.sh \
acloca12.sh \
acloca13.sh \
acloca14.sh \
acloca15.sh \
acloca16.sh \
acloca17.sh \
acloca18.sh \
acloca19.sh \
acloca20.sh \
acloca21.sh \
acloca22.sh \
acloca23.sh \
aclocal-acdir.sh \
aclocal-install-absdir.sh \
aclocal-print-acdir.sh \
aclocal-path.sh \
aclocal-path-install.sh \
aclocal-path-install-serial.sh \
aclocal-path-nonexistent.sh \
aclocal-path-precedence.sh \
aclocal-install-fail.sh \
aclocal-install-mkdir.sh \
aclocal-no-install-no-mkdir.sh \
aclocal-verbose-install.sh \
ac-output-old.tap \
acsilent.sh \
acsubst.sh \
acsubst2.sh \
add-missing.tap \
all.sh \
all2.sh \
alloca.sh \
alloca2.sh \
alpha.sh \
alpha2.sh \
amhello-cflags.sh \
amhello-cross-compile.sh \
amhello-binpkg.sh \
amassign.sh \
ammissing.sh \
amopt.sh \
amopts-location.sh \
amopts-variable-expansion.sh \
amsubst.sh \
ansi2knr-no-more.sh \
ar-lib.sh \
ar-lib2.sh \
ar-lib3.sh \
ar-lib4.sh \
ar-lib5a.sh \
ar-lib5b.sh \
ar-lib6a.sh \
ar-lib6b.sh \
ar-lib7.sh \
ar.sh \
ar2.sh \
ar3.sh \
ar4.sh \
ar5.sh \
asm.sh \
asm2.sh \
asm3.sh \
autodist.sh \
autodist-subdir.sh \
autodist-acconfig.sh \
autodist-acconfig-no-subdir.sh \
autodist-aclocal-m4.sh \
autodist-config-headers.sh \
autodist-configure-no-subdir.sh \
autodist-no-duplicate.sh \
autodist-stamp-vti.sh \
autohdr.sh \
autohdr2.sh \
autohdr3.sh \
autohdr4.sh \
autohdrdry.sh \
automake-cmdline.tap \
auxdir.sh \
auxdir6.sh \
auxdir7.sh \
auxdir8.sh \
auxdir-autodetect.sh \
auxdir-computed.tap \
auxdir-misplaced.sh \
auxdir-nonexistent.sh \
auxdir-unportable.tap \
backcompat.sh \
backcompat2.sh \
backcompat3.sh \
backcompat4.sh \
backcompat5.sh \
backcompat6.sh \
backsl.sh \
backsl2.sh \
backsl3.sh \
backsl4.sh \
badline.sh \
badopt.sh \
badprog.sh \
block.sh \
bsource.sh \
candist.sh \
canon.sh \
canon2.sh \
canon3.sh \
canon4.sh \
canon5.sh \
canon6.sh \
canon7.sh \
canon8.sh \
canon-name.sh \
ccnoco.sh \
ccnoco2.sh \
ccnoco3.sh \
check.sh \
check2.sh \
check3.sh \
check4.sh \
check5.sh \
check6.sh \
check7.sh \
check8.sh \
check10.sh \
check11.sh \
check12.sh \
check-subst.sh \
check-subst-prog.sh \
check-exported-srcdir.sh \
check-fd-redirect.sh \
check-tests-in-builddir.sh \
check-no-test-driver.sh \
check-concurrency-bug9245.sh \
checkall.sh \
clean.sh \
clean2.sh \
colneq.sh \
colneq2.sh \
colneq3.sh \
colon.sh \
colon2.sh \
colon3.sh \
colon4.sh \
colon5.sh \
colon6.sh \
colon7.sh \
color.sh \
color2.sh \
comment.sh \
comment2.sh \
comment3.sh \
comment4.sh \
comment5.sh \
comment6.sh \
comment7.sh \
comment8.sh \
comment9.sh \
commen10.sh \
commen11.sh \
comments-in-var-def.sh \
compile.sh \
compile2.sh \
compile3.sh \
compile4.sh \
compile5.sh \
compile6.sh \
compile_f90_c_cxx.sh \
compile_f_c_cxx.sh \
cond-basic.sh \
cond.sh \
cond2.sh \
cond3.sh \
cond4.sh \
cond5.sh \
cond6.sh \
cond7.sh \
cond8.sh \
cond9.sh \
cond10.sh \
cond11.sh \
cond13.sh \
cond14.sh \
cond15.sh \
cond16.sh \
cond17.sh \
cond18.sh \
cond19.sh \
cond20.sh \
cond21.sh \
cond22.sh \
cond23.sh \
cond24.sh \
cond25.sh \
cond26.sh \
cond27.sh \
cond28.sh \
cond29.sh \
cond30.sh \
cond31.sh \
cond32.sh \
cond33.sh \
cond34.sh \
cond35.sh \
cond36.sh \
cond37.sh \
cond38.sh \
cond39.sh \
cond40.sh \
cond41.sh \
cond42.sh \
cond43.sh \
cond44.sh \
cond45.sh \
cond46.sh \
condd.sh \
condhook.sh \
condhook2.sh \
condinc.sh \
condinc2.sh \
condlib.sh \
condman2.sh \
condman3.sh \
configure.sh \
confdeps.sh \
conff.sh \
conff2.sh \
conffile-leading-dot.sh \
confh.sh \
confh4.sh \
confh5.sh \
confh6.sh \
confh7.sh \
confh8.sh \
confincl.sh \
conflnk.sh \
conflnk2.sh \
conflnk3.sh \
conflnk4.sh \
confsub.sh \
confvar.sh \
confvar2.sh \
copy.sh \
cscope.tap \
cscope2.sh \
cscope3.sh \
cxx.sh \
cxx2.sh \
cxxcpp.sh \
cxxlibobj.sh \
cxxlink.sh \
cxxnoc.sh \
cxxo.sh \
cygnus-check-without-all.sh \
cygnus-dependency-tracking.sh \
cygnus-imply-foreign.sh \
cygnus-no-dist.sh \
cygnus-no-installinfo.sh \
cygnus-requires-maintainer-mode.sh \
cygwin32.sh \
dash.sh \
defun.sh \
defun2.sh \
dejagnu.sh \
dejagnu2.sh \
dejagnu3.sh \
dejagnu4.sh \
dejagnu5.sh \
dejagnu6.sh \
dejagnu7.sh \
dejagnu-absolute-builddir.sh \
dejagnu-relative-srcdir.sh \
dejagnu-siteexp-extend.sh \
dejagnu-siteexp-append.sh \
dejagnu-siteexp-useredit.sh \
deleted-am.sh \
deleted-m4.sh \
depacl2.sh \
depcomp.sh \
depcomp2.sh \
depcomp8a.sh \
depcomp8b.sh \
depdist.sh \
depend.sh \
depend3.sh \
depend4.sh \
depend5.sh \
depend6.sh \
deprecated-acinit.sh \
destdir.sh \
dirlist.sh \
dirlist2.sh \
dirlist-abspath.sh \
discover.sh \
dist-formats.tap \
dist-auxdir-many-subdirs.sh \
dist-auxfile-2.sh \
dist-auxfile.sh \
dist-included-parent-dir.sh \
dist-missing-am.sh \
dist-missing-included-m4.sh \
dist-missing-m4.sh \
dist-readonly.sh \
dist-repeated.sh \
dist-pr109765.sh \
distcleancheck.sh \
distcom2.sh \
distcom3.sh \
distcom4.sh \
distcom5.sh \
distcom-subdir.sh \
distdir.sh \
disthook.sh \
distlinks.sh \
distlinksbrk.sh \
distname.sh \
distcheck-configure-flags.sh \
distcheck-configure-flags-am.sh \
distcheck-configure-flags-subpkg.sh \
distcheck-hook.sh \
distcheck-hook2.sh \
distcheck-writable-srcdir.sh \
distcheck-missing-m4.sh \
distcheck-outdated-m4.sh \
distcheck-override-infodir.sh \
distcheck-pr9579.sh \
distcheck-pr10470.sh \
dmalloc.sh \
doc-parsing-buglets-colneq-subst.sh \
doc-parsing-buglets-tabs.sh \
dollar.sh \
dollarvar.sh \
dollarvar2.sh \
double.sh \
dup2.sh \
else.sh \
empty.sh \
empty2.sh \
empty3.sh \
empty4.sh \
exdir.sh \
exdir2.sh \
exdir3.sh \
exeext.sh \
exeext2.sh \
exeext3.sh \
exeext4.sh \
exsource.sh \
ext.sh \
ext2.sh \
ext3.sh \
extra.sh \
extra2.sh \
extra3.sh \
extra4.sh \
extra5.sh \
extra6.sh \
extra7.sh \
extra8.sh \
extra9.sh \
extra10.sh \
extra11.sh \
extra12.sh \
extra-programs-empty.sh \
extra-portability.sh \
extra-portability2.sh \
extra-portability3.sh \
extradep.sh \
extradep2.sh \
f90only.sh \
flavor.sh \
flibs.sh \
fn99.sh \
fn99subdir.sh \
fnoc.sh \
fo.sh \
forcemiss.sh \
forcemiss2.sh \
fort1.sh \
fort2.sh \
fort4.sh \
fort5.sh \
fonly.sh \
fortdep.sh \
gcj.sh \
gcj2.sh \
gcj3.sh \
gcj4.sh \
gcj5.sh \
gcj6.sh \
gettext.sh \
gettext2.sh \
gettext3.sh \
gnumake.sh \
gnuwarn.sh \
gnuwarn2.sh \
gnits.sh \
gnits2.sh \
gnits3.sh \
hdr-vars-defined-once.sh \
header.sh \
help.sh \
help2.sh \
help3.sh \
help4.sh \
help-depend.sh \
help-depend2.sh \
help-dmalloc.sh \
help-init.sh \
help-lispdir.sh \
help-multilib.sh \
help-python.sh \
help-silent.sh \
help-upc.sh \
hfs.sh \
implicit.sh \
info.sh \
init.sh \
init2.sh \
insh2.sh \
install2.sh \
installdir.sh \
instsh.sh \
instsh2.sh \
instsh3.sh \
instdat.sh \
instdat2.sh \
instdir.sh \
instdir2.sh \
instdir-cond.sh \
instdir-cond2.sh \
instdir-no-empty.sh \
instdir-java.sh \
instdir-lisp.sh \
instdir-ltlib.sh \
instdir-prog.sh \
instdir-python.sh \
instdir-texi.sh \
instexec.sh \
instfail.sh \
instfail-info.sh \
instfail-java.sh \
instfail-libtool.sh \
insthook.sh \
instman.sh \
instman2.sh \
instmany.sh \
instmany-mans.sh \
instmany-python.sh \
install-info-dir.sh \
interp.sh \
interp2.sh \
java.sh \
java2.sh \
java3.sh \
javadir-undefined.sh \
javaflags.sh \
java-check.sh \
java-clean.sh \
java-compile-install.sh \
java-compile-run-flat.sh \
java-compile-run-nested.sh \
java-empty-classpath.sh \
javaprim.sh \
javasubst.sh \
java-extra.sh \
java-mix.sh \
java-no-duplicate.sh \
java-nobase.sh \
java-noinst.sh \
java-rebuild.sh \
java-sources.sh \
java-uninstall.sh \
ldadd.sh \
ldflags.sh \
lex.sh \
lex2.sh \
lex3.sh \
lex5.sh \
lexcpp.sh \
lexvpath.sh \
lex-subobj-nodep.sh \
lex-lib.sh \
lex-lib-external.sh \
lex-libobj.sh \
lex-noyywrap.sh \
lex-clean-cxx.sh \
lex-clean.sh \
lex-depend-cxx.sh \
lex-depend-grep.sh \
lex-depend.sh \
lex-line.sh \
lex-nodist.sh \
lex-pr204.sh \
lflags.sh \
lflags2.sh \
libexec.sh \
libobj-basic.sh \
libobj2.sh \
libobj3.sh \
libobj4.sh \
libobj5.sh \
libobj7.sh \
libobj10.sh \
libobj12.sh \
libobj13.sh \
libobj14.sh \
libobj15a.sh \
libobj15b.sh \
libobj15c.sh \
libobj16a.sh \
libobj16b.sh \
libobj17.sh \
libobj18.sh \
libobj19.sh \
libobj20a.sh \
libobj20b.sh \
libobj20c.sh \
library.sh \
library2.sh \
library3.sh \
libtool.sh \
libtool2.sh \
libtool3.sh \
libtool4.sh \
libtool5.sh \
libtool6.sh \
libtool7.sh \
libtool8.sh \
libtool9.sh \
libtoo10.sh \
libtoo11.sh \
license.sh \
license2.sh \
link_c_cxx.sh \
link_cond.sh \
link_dist.sh \
link_f90_only.sh \
link_fc.sh \
link_fccxx.sh \
link_fcxx.sh \
link_f_only.sh \
link_override.sh \
lisp2.sh \
lisp3.sh \
lisp4.sh \
lisp5.sh \
lisp6.sh \
lisp7.sh \
lisp8.sh \
lispdry.sh \
listval.sh \
location.sh \
longline.sh \
longlin2.sh \
ltcond.sh \
ltcond2.sh \
ltconv.sh \
ltdeps.sh \
ltinit.sh \
ltinstloc.sh \
ltlibobjs.sh \
ltlibsrc.sh \
ltorder.sh \
lzma.sh \
m4-inclusion.sh \
maintclean.sh \
maintclean-vpath.sh \
maintmode-configure-msg.sh \
make.sh \
makefile-deps.sh \
makej.sh \
makej2.sh \
maken.sh \
maken3.sh \
make-dryrun.tap \
makevars.sh \
man.sh \
man2.sh \
man3.sh \
man4.sh \
man5.sh \
man6.sh \
man7.sh \
man8.sh \
mdate.sh \
mdate2.sh \
mdate3.sh \
mdate4.sh \
mdate5.sh \
mdate6.sh \
missing.sh \
missing2.sh \
missing3.sh \
missing4.sh \
missing5.sh \
missing6.sh \
missing-auxfile-stops-makefiles-creation.sh \
mkinstall.sh \
mkinst2.sh \
mkinst3.sh \
mmode.sh \
mmodely.sh \
multlib.sh \
no-extra-makefile-code.sh \
no-outdir-option.sh \
nobase.sh \
nobase-libtool.sh \
nobase-python.sh \
nobase-nodist.sh \
nodef.sh \
nodef2.sh \
nodep.sh \
nodep2.sh \
nodepcomp.sh \
nodist.sh \
nodist2.sh \
nodist3.sh \
noinst.sh \
noinstdir.sh \
nolink.sh \
nostdinc.sh \
notrans.sh \
number.sh \
objc.sh \
objc2.sh \
objext-pr10128.sh \
obsolete.sh \
oldvars.sh \
order.sh \
output.sh \
output2.sh \
output3.sh \
output4.sh \
output5.sh \
output6.sh \
output7.sh \
output8.sh \
output9.sh \
output10.sh \
output11.sh \
output12.sh \
output13.sh \
output-order.sh \
override-conditional-1.sh \
override-conditional-2.sh \
override-html.sh \
override-suggest-local.sh \
parallel-am.sh \
parallel-am2.sh \
parallel-am3.sh \
serial-tests.sh \
parallel-tests.sh \
parallel-tests2.sh \
parallel-tests3.sh \
parallel-tests5.sh \
parallel-tests6.sh \
parallel-tests8.sh \
parallel-tests9.sh \
parallel-tests10.sh \
parallel-tests-exeext.sh \
parallel-tests-suffix.sh \
parallel-tests-suffix-prog.sh \
parallel-tests-log-compiler-1.sh \
parallel-tests-log-compiler-2.sh \
parallel-tests-dry-run-1.sh \
parallel-tests-dry-run-2.sh \
parallel-tests-fd-redirect.sh \
parallel-tests-fd-redirect-exeext.sh \
parallel-tests-extra-programs.sh \
parallel-tests-unreadable.sh \
parallel-tests-subdir.sh \
parallel-tests-interrupt.tap \
parallel-tests-reset-term.sh \
parallel-tests-harderror.sh \
parallel-tests-log-override-1.sh \
parallel-tests-log-override-2.sh \
parallel-tests-log-override-recheck.sh \
parallel-tests-log-compiler-example.sh \
parallel-tests-cmdline-override.sh \
parallel-tests-fork-bomb.sh \
parallel-tests-empty-testlogs.sh \
parallel-tests-driver-install.sh \
parallel-tests-no-color-in-log.sh \
parallel-tests-no-spurious-summary.sh \
parallel-tests-exit-statuses.sh \
parallel-tests-console-output.sh \
parallel-tests-once.sh \
parallel-tests-trailing-bslash.sh \
parallel-tests-many.sh \
tests-environment.sh \
am-tests-environment.sh \
tests-environment-backcompat.sh \
testsuite-summary-color.sh \
testsuite-summary-count.sh \
testsuite-summary-count-many.sh \
testsuite-summary-reference-log.sh \
test-driver-acsubst.sh \
test-driver-cond.sh \
test-driver-custom-no-extra-driver.sh \
test-driver-custom.sh \
test-driver-custom-xfail-tests.sh \
test-driver-custom-multitest.sh \
test-driver-custom-multitest-recheck.sh \
test-driver-custom-multitest-recheck2.sh \
test-driver-create-log-dir.sh \
test-driver-strip-vpath.sh \
test-driver-trs-suffix-registered.sh \
test-driver-fail.sh \
test-driver-is-distributed.sh \
test-harness-vpath-rewrite.sh \
test-log.sh \
test-logs-repeated.sh \
test-metadata-global-log.sh \
test-metadata-global-result.sh \
test-metadata-recheck.sh \
test-metadata-results.sh \
test-missing.sh \
test-missing2.sh \
test-trs-basic.sh \
test-trs-recover.sh \
test-trs-recover2.sh \
test-extensions.sh \
test-extensions-cond.sh \
parse.sh \
percent.sh \
percent2.sh \
phony.sh \
pluseq.sh \
pluseq2.sh \
pluseq3.sh \
pluseq4.sh \
pluseq5.sh \
pluseq6.sh \
pluseq7.sh \
pluseq8.sh \
pluseq9.sh \
pluseq10.sh \
pluseq11.sh \
posixsubst-data.sh \
posixsubst-extradist.sh \
posixsubst-ldadd.sh \
posixsubst-libraries.sh \
posixsubst-ltlibraries.sh \
posixsubst-programs.sh \
posixsubst-scripts.sh \
posixsubst-sources.sh \
posixsubst-tests.sh \
postproc.sh \
ppf77.sh \
pr2.sh \
pr9.sh \
pr72.sh \
pr87.sh \
pr211.sh \
pr220.sh \
pr224.sh \
pr229.sh \
pr243.sh \
pr266.sh \
pr279.sh \
pr279-2.sh \
pr287.sh \
pr300-lib.sh \
pr300-ltlib.sh \
pr300-prog.sh \
pr307.sh \
pr401.sh \
pr401b.sh \
pr401c.sh \
prefix.sh \
primary.sh \
primary2.sh \
primary3.sh \
primary-prefix-invalid-couples.tap \
primary-prefix-valid-couples.sh \
primary-prefix-couples-force-valid.sh \
primary-prefix-couples-documented-valid.sh \
print-libdir.sh \
proginst.sh \
programs-primary-rewritten.sh \
py-compile-basic.sh \
py-compile-basic2.sh \
py-compile-basedir.sh \
py-compile-destdir.sh \
py-compile-env.sh \
py-compile-option-terminate.sh \
py-compile-usage.sh \
python.sh \
python2.sh \
python3.sh \
python4.sh \
python5.sh \
python5b.sh \
python6.sh \
python7.sh \
python8.sh \
python9.sh \
python10.sh \
python11.sh \
python12.sh \
python-dist.sh \
python-vars.sh \
python-virtualenv.sh \
python-pr10995.sh \
recurs.sh \
recurs2.sh \
remake.sh \
remake1a.sh \
remake2.sh \
remake3.sh \
remake3a.sh \
remake4.sh \
remake5.sh \
remake6.sh \
remake7.sh \
remake8a.sh \
remake8b.sh \
remake9a.sh \
remake9b.sh \
remake9c.sh \
remake9d.sh \
remake10a.sh \
remake10b.sh \
remake10c.sh \
remake11.sh \
remake12.sh \
remake-all-1.sh \
remake-all-2.sh \
remake-subdir-from-subdir.sh \
remake-subdir-gnu.sh \
remake-subdir.sh \
remake-subdir2.sh \
remake-subdir-long-time.sh \
remake-gnulib-add-acsubst.sh \
remake-gnulib-add-header.sh \
remake-gnulib-remove-header.sh \
remake-moved-m4-file.sh \
remake-deleted-m4-file.sh \
remake-renamed-m4-file.sh \
remake-renamed-m4-macro-and-file.sh \
remake-renamed-m4-macro.sh \
remake-am-pr10111.sh \
remake-m4-pr10111.sh \
remake-deleted-am-2.sh \
remake-deleted-am-subdir.sh \
remake-deleted-am.sh \
remake-renamed-am.sh \
pr8365-remake-timing.sh \
req.sh \
reqd.sh \
reqd2.sh \
repeated-options.sh \
rst-formatting.sh \
rulepat.sh \
self-check-cleanup.tap \
self-check-configure-help.sh \
self-check-dir.tap \
self-check-env-sanitize.tap \
self-check-exit.tap \
self-check-explicit-skips.sh \
self-check-is_newest.tap \
self-check-me.tap \
self-check-reexec.tap \
self-check-report.sh \
self-check-sanity.sh \
self-check-seq.tap \
self-check-is-blocked-signal.tap \
self-check-tap.sh \
self-check-unindent.tap \
sanity.sh \
scripts.sh \
seenc.sh \
silent.sh \
silent2.sh \
silent3.sh \
silent4.sh \
silent6.sh \
silent7.sh \
silent8.sh \
silent9.sh \
silentcxx.sh \
silentcxx-gcc.sh \
silentf77.sh \
silentf90.sh \
silent-amopts.sh \
silent-many-gcc.sh \
silent-many-generic.sh \
silent-nowarn.sh \
silent-configsite.sh \
silent-nested-vars.sh \
silent-lex.sh \
silent-yacc.sh \
silent-yacc-headers.sh \
srcsub.sh \
srcsub2.sh \
space.sh \
specflg.sh \
specflg2.sh \
specflg3.sh \
specflg6.sh \
specflg7.sh \
specflg8.sh \
specflg9.sh \
specflg10.sh \
specflg-dummy.sh \
spell.sh \
spell2.sh \
spell3.sh \
spelling.sh \
spy.sh \
spy-rm.tap \
stdinc.sh \
stamph2.sh \
stdlib.sh \
stdlib2.sh \
strictness-override.sh \
strictness-precedence.sh \
strip.sh \
strip2.sh \
strip3.sh \
subdir.sh \
subdir2.sh \
subdir3.sh \
subdir4.sh \
subdir5.sh \
subdir6.sh \
subdir7.sh \
subdir8.sh \
subdir9.sh \
subdir10.sh \
subdirbuiltsources.sh \
subcond.sh \
subcond2.sh \
subcond3.sh \
subobj.sh \
subobj2.sh \
subobj4.sh \
subobj5.sh \
subobj6.sh \
subobj7.sh \
subobj8.sh \
subobj9.sh \
subobj10.sh \
subobj11a.sh \
subobj11b.sh \
subobj11c.sh \
subobjname.sh \
subpkg.sh \
subpkg2.sh \
subpkg3.sh \
subpkg4.sh \
subpkg-yacc.sh \
subst.sh \
subst3.sh \
subst4.sh \
subst5.sh \
subst-no-trailing-empty-line.sh \
substref.sh \
substre2.sh \
substtarg.sh \
suffix.sh \
suffix2.sh \
suffix3.tap \
suffix4.sh \
suffix5.sh \
suffix6.sh \
suffix6b.sh \
suffix6c.sh \
suffix7.sh \
suffix8.tap \
suffix9.sh \
suffix10.tap \
suffix11.tap \
suffix12.sh \
suffix13.sh \
suffix-chain.tap \
symlink.sh \
symlink2.sh \
syntax.sh \
tap-ambiguous-directive.sh \
tap-autonumber.sh \
tap-bailout.sh \
tap-bailout-leading-space.sh \
tap-bailout-and-logging.sh \
tap-bailout-suppress-badexit.sh \
tap-bailout-suppress-later-diagnostic.sh \
tap-bailout-suppress-later-errors.sh \
tap-color.sh \
tap-deps.sh \
tap-diagnostic.sh \
tap-empty-diagnostic.sh \
tap-empty.sh \
tap-escape-directive.sh \
tap-escape-directive-2.sh \
tap-exit.sh \
tap-signal.tap \
tap-fancy.sh \
tap-fancy2.sh \
tap-global-log.sh \
tap-global-result.sh \
tap-log.sh \
tap-msg0-result.sh \
tap-msg0-directive.sh \
tap-msg0-planskip.sh \
tap-msg0-bailout.sh \
tap-msg0-misc.sh \
tap-merge-stdout-stderr.sh \
tap-no-merge-stdout-stderr.sh \
tap-no-disable-hard-error.sh \
tap-no-spurious-summary.sh \
tap-no-spurious-numbers.sh \
tap-no-spurious.sh \
tap-not-ok-skip.sh \
tap-number-wordboundary.sh \
tap-numeric-description.sh \
tap-negative-numbers.sh \
tap-numbers-leading-zero.sh \
tap-out-of-order.sh \
tap-passthrough.sh \
tap-passthrough-exit.sh \
tap-plan.sh \
tap-plan-corner.sh \
tap-plan-errors.sh \
tap-plan-middle.sh \
tap-plan-whitespace.sh \
tap-plan-leading-zero.sh \
tap-plan-malformed.sh \
tap-missing-plan-and-bad-exit.sh \
tap-planskip.sh \
tap-planskip-late.sh \
tap-planskip-and-logging.sh \
tap-planskip-unplanned.sh \
tap-planskip-unplanned-corner.sh \
tap-planskip-case-insensitive.sh \
tap-planskip-whitespace.sh \
tap-planskip-badexit.sh \
tap-planskip-bailout.sh \
tap-planskip-later-errors.sh \
tap-realtime.sh \
tap-test-number-0.sh \
tap-recheck-logs.sh \
tap-result-comment.sh \
tap-todo-skip-together.sh \
tap-todo-skip-whitespace.sh \
tap-todo-skip.sh \
tap-unplanned.sh \
tap-whitespace-normalization.sh \
tap-with-and-without-number.sh \
tap-xfail-tests.sh \
tap-common-setup.sh \
tap-bad-prog.tap \
tap-basic.sh \
tap-diagnostic-custom.sh \
tap-driver-stderr.sh \
tap-doc.sh \
tap-doc2.sh \
tap-more.sh \
tap-more2.sh \
tap-recheck.sh \
tap-summary.sh \
tap-summary-color.sh \
tags.sh \
tags2.sh \
tagsub.sh \
tar.sh \
tar2.sh \
tar3.sh \
tar-override.sh \
target-cflags.sh \
targetclash.sh \
tests-environment-fd-redirect.sh \
tests-environment-and-log-compiler.sh \
txinfo.sh \
txinfo2.sh \
txinfo3.sh \
txinfo4.sh \
txinfo5.sh \
txinfo5b.sh \
txinfo6.sh \
txinfo7.sh \
txinfo8.sh \
txinfo9.sh \
txinfo10.sh \
txinfo13.sh \
txinfo16.sh \
txinfo17.sh \
txinfo19.sh \
txinfo20.sh \
txinfo21.sh \
txinfo22.sh \
txinfo23.sh \
txinfo24.sh \
txinfo25.sh \
txinfo26.sh \
txinfo27.sh \
txinfo28.sh \
txinfo29.sh \
txinfo30.sh \
txinfo31.sh \
txinfo32.sh \
txinfo33.sh \
txinfo-no-clutter.sh \
txinfo-unrecognized-extension.sh \
transform.sh \
transform2.sh \
transform3.sh \
uninstall-fail.sh \
uninstall-pr9578.sh \
unused.sh \
upc.sh \
upc2.sh \
upc3.sh \
vala.sh \
vala1.sh \
vala2.sh \
vala3.sh \
vala4.sh \
vala5.sh \
vala-vpath.sh \
vala-mix.sh \
vala-mix2.sh \
vars.sh \
vars3.sh \
vartar.sh \
vartypos.sh \
vartypo2.sh \
version.sh \
version2.sh \
version3.sh \
version4.sh \
version6.sh \
version7.sh \
version8.sh \
vpath.sh \
vtexi.sh \
vtexi2.sh \
vtexi3.sh \
vtexi4.sh \
warnings-override.sh \
warnings-precedence.sh \
warnings-strictness-interactions.sh \
warnings-unknown.sh \
warnopts.sh \
warnings-win-over-strictness.sh \
warning-groups-win-over-strictness.sh \
werror.sh \
werror2.sh \
werror3.sh \
werror4.sh \
whoami.sh \
xsource.sh \
yacc.sh \
yacc2.sh \
yacc4.sh \
yacc5.sh \
yacc7.sh \
yacc8.sh \
yaccdry.sh \
yaccpp.sh \
yaccvpath.sh \
yacc-auxdir.sh \
yacc-basic.sh \
yacc-cxx.sh \
yacc-bison-skeleton-cxx.sh \
yacc-bison-skeleton.sh \
yacc-clean.sh \
yacc-clean-cxx.sh \
yacc-d-basic.sh \
yacc-d-cxx.sh \
yacc-d-vpath.sh \
yacc-deleted-headers.sh \
yacc-depend.sh \
yacc-depend2.sh \
yacc-dist-nobuild-subdir.sh \
yacc-dist-nobuild.sh \
yacc-line.sh \
yacc-mix-c-cxx.sh \
yacc-nodist.sh \
yacc-pr204.sh \
yacc-weirdnames.sh \
yflags.sh \
yflags2.sh \
yflags-cmdline-override.sh \
yflags-conditional.sh \
yflags-d-false-positives.sh \
yflags-force-conditional.sh \
yflags-force-override.sh \
yflags-var-expand.sh \
libtool-macros.sh \
gettext-macros.sh

print-list-of-tests:
	@echo $(handwritten_TESTS)
.PHONY: print-list-of-tests
