#! /bin/sh
# Copyright (C) 2002-2012 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Make sure that derivations work with .lo too.
# Also check suffixes containing the'-' character.
# (related to PR/37)

required='cc libtoolize yacc'
. ./defs || Exit 1

cat >>configure.ac <<EOF
AC_PROG_CC
AC_PROG_YACC
AM_PROG_AR
AC_PROG_LIBTOOL
AC_OUTPUT
EOF

cat >Makefile.am << 'END'
lib_LTLIBRARIES = libfoo.la
nodist_libfoo_la_SOURCES = foo.y
CLEANFILES = $(nodist_libfoo_la_SOURCES)
EXTRA_DIST = $(nodist_libfoo_la_SOURCES:.y=.x-x)
%.y: %.x-x
	rm -f $@ $@-t
## The leading ':;' works around a bug in bash <= 3.2.
	:; { echo '/* autogenerated */' \
	  && echo '%{' \
	  && echo 'int yylex () {return 0;}' \
	  && echo 'void yyerror (char *s) {}' \
	  && echo '%}' \
	  && echo '%%' \
	  && echo "foobar : 'f' 'o' 'o' 'b' 'a' 'r' {};" \
	  && echo '%%' \
	  && cat $<; \
	} > $@-t
	mv -f $@-t $@
.PHONY: test
test:
	echo $(libfoo_la_OBJECTS) | grep '^foo\.lo$$'
END

cat > foo.x-x << 'END'
int foo (void) { return yyparse(); }
END

libtoolize --force
$ACLOCAL
$AUTOCONF
$AUTOMAKE --add-missing

./configure

$MAKE test
$MAKE all
test -f libfoo.la
$MAKE distcheck

:
