package ParserTable;

use Exporter;
use Tree;

our @ISA=qw(Exporter);
our @Export=qw(@table $accept);

our $accept=20;

our @table=(
		{makerule => 9, include => 4, comment => 2, stmt => 7, conditional => 11, stmts => 6, ifblock => 12, value => 1, input => 5, includerule => 10, optionlist => 15, automakerule => 8, if => 3, commentlist => 14, lhs => 13},
		{reduce => [1,  \&lhs], ':' => 16, '_' => 17},
		{reduce => [1,  \&commentlist]},
		{value => 18},
		{value => 19},
		{end => 20},
		{conditional => 11, include => 4, comment => 2, stmt => 21, makerule => 9, if => 3, reduce => [1,  \&input], lhs => 13, commentlist => 14, optionlist => 15, automakerule => 8, includerule => 10, ifblock => 12, value => 1},
		{newline => 22},
		{reduce => [1,  \&stmt]},
		{reduce => [1,  \&stmt]},
		{reduce => [1,  \&stmt]},
		{reduce => [1,  \&stmt]},
		{reduce => [0,  \&optionalelse], optionalelse => 24, else => 23},
		{'+' => 26, '=' => 25},
		{reduce => [1,  \&stmt], comment => 27},
		{SCRIPTS => 35, LIBRARIES => 30, LISP => 32, HEADERS => 37, PYTHON => 33, PROGRAMS => 29, LTLIBRARIES => 31, JAVA => 34, DATA => 36, TEXINFOS => 39, primaries => 40, value => 28, MASN => 38},
		{rhsval => 41, rhs => 42},
		{reduce => [2,  \&optionlist]},
		{newline => 43},
		{reduce => [2,  \&includerule]},
		{},
		{newline => 44},
		{reduce => [2,  \&stmts]},
		{newline => 45},
		{endif => 46},
		{optionalrhs => 47, rhsval => 41, rhs => 48, reduce => [0,  \&optionalrhs]},
		{'=' => 49},
		{reduce => [2,  \&commentlist]},
		{reduce => [1,  \&primaries], '_' => 50},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [2,  \&lhs]},
		{reduce => [1,  \&rhs]},
		{rhsval => 51, reduce => [3,  \&makerule]},
		{comment => 2, stmt => 7, include => 4, makerule => 9, stmts => 52, conditional => 11, includerule => 10, value => 1, ifblock => 12, lhs => 13, commentlist => 14, if => 3, automakerule => 8, optionlist => 15},
		{reduce => [3,  \&stmts]},
		{stmts => 53, conditional => 11, stmt => 7, comment => 2, include => 4, makerule => 9, commentlist => 14, lhs => 13, if => 3, automakerule => 8, optionlist => 15, includerule => 10, ifblock => 12, value => 1},
		{value => 54, optionalcond => 55, reduce => [0,  \&optionalcond]},
		{commentlist => 57, reduce => [0,  \&optionalcomments], optionalcomments => 56, comment => 2},
		{reduce => [1,  \&optionalrhs], rhsval => 51},
		{rhsval => 41, optionalrhs => 58, rhs => 48, reduce => [0,  \&optionalrhs]},
		{reduce => [3,  \&optionlist]},
		{reduce => [2,  \&rhs]},
		{value => 1, ifblock => 12, includerule => 10, optionlist => 15, automakerule => 8, if => 3, lhs => 13, reduce => [4,  \&ifblock], commentlist => 14, makerule => 9, include => 4, stmt => 21, comment => 2, conditional => 11},
		{comment => 2, stmt => 21, include => 4, makerule => 9, conditional => 11, includerule => 10, value => 1, ifblock => 12, lhs => 13, reduce => [3,  \&optionalelse], commentlist => 14, if => 3, automakerule => 8, optionlist => 15},
		{reduce => [1,  \&optionalcond]},
		{reduce => [4,  \&conditional]},
		{reduce => [4,  \&automakerule]},
		{comment => 27, reduce => [1,  \&optionalcomments]},
		{comment => 2, commentlist => 57, reduce => [0,  \&optionalcomments], optionalcomments => 59},
		{reduce => [5,  \&automakerule]}
);