package ParserTable;

use Exporter;
use Tree;

our @ISA=qw(Exporter);
our @Export=qw(@table $accept);

our $accept=20;

our @table=(
		{optionlist => 15, commentlist => 14, if => 3, ifblock => 12, includerule => 10, stmt => 7, automakerule => 8, value => 1, stmts => 6, comment => 2, include => 4, conditional => 11, input => 5, lhs => 13, makerule => 9},
		{reduce => [1,  \&lhs], ':' => 16, '_' => 17},
		{reduce => [1,  \&commentlist]},
		{value => 18},
		{value => 19},
		{end => 20},
		{optionlist => 15, commentlist => 14, if => 3, ifblock => 12, includerule => 10, stmt => 21, automakerule => 8, value => 1, comment => 2, conditional => 11, include => 4, reduce => [1,  \&input], lhs => 13, makerule => 9},
		{newline => 22},
		{reduce => [1,  \&stmt]},
		{reduce => [1,  \&stmt]},
		{reduce => [1,  \&stmt]},
		{reduce => [1,  \&stmt]},
		{reduce => [0,  \&optionalelse], else => 23, optionalelse => 24},
		{'+' => 26, '=' => 25},
		{comment => 27, reduce => [1,  \&stmt]},
		{TEXINFOS => 39, LISP => 32, HEADERS => 37, SCRIPTS => 35, value => 28, primaries => 40, LIBRARIES => 30, PYTHON => 33, PROGRAMS => 29, MASN => 38, JAVA => 34, LTLIBRARIES => 31, DATA => 36},
		{rhs => 42, rhsval => 41},
		{reduce => [2,  \&optionlist]},
		{newline => 43},
		{reduce => [2,  \&includerule]},
		{},
		{newline => 44},
		{reduce => [2,  \&stmts]},
		{newline => 45},
		{endif => 46},
		{optionalrhs => 47, rhsval => 41, reduce => [0,  \&optionalrhs], rhs => 48},
		{'=' => 49},
		{reduce => [2,  \&commentlist]},
		{'_' => 50, reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [1,  \&primaries]},
		{reduce => [2,  \&lhs]},
		{reduce => [1,  \&rhs]},
		{reduce => [3,  \&makerule], rhsval => 51},
		{if => 3, includerule => 10, ifblock => 12, stmt => 7, automakerule => 8, optionlist => 15, commentlist => 14, include => 4, conditional => 11, lhs => 13, makerule => 9, value => 1, stmts => 52, comment => 2},
		{reduce => [3,  \&stmts]},
		{automakerule => 8, stmt => 7, ifblock => 12, includerule => 10, if => 3, commentlist => 14, optionlist => 15, makerule => 9, lhs => 13, include => 4, conditional => 11, comment => 2, stmts => 53, value => 1},
		{value => 54, optionalcond => 55, reduce => [0,  \&optionalcond]},
		{reduce => [0,  \&optionalcomments], comment => 2, optionalcomments => 56, commentlist => 57},
		{reduce => [1,  \&optionalrhs], rhsval => 51},
		{optionalrhs => 58, reduce => [0,  \&optionalrhs], rhsval => 41, rhs => 48},
		{reduce => [3,  \&optionlist]},
		{reduce => [2,  \&rhs]},
		{commentlist => 14, optionlist => 15, automakerule => 8, stmt => 21, ifblock => 12, includerule => 10, if => 3, comment => 2, value => 1, reduce => [4,  \&ifblock], lhs => 13, makerule => 9, conditional => 11, include => 4},
		{if => 3, ifblock => 12, includerule => 10, stmt => 21, automakerule => 8, optionlist => 15, commentlist => 14, conditional => 11, include => 4, reduce => [3,  \&optionalelse], lhs => 13, makerule => 9, value => 1, comment => 2},
		{reduce => [1,  \&optionalcond]},
		{reduce => [4,  \&conditional]},
		{reduce => [4,  \&automakerule]},
		{comment => 27, reduce => [1,  \&optionalcomments]},
		{reduce => [0,  \&optionalcomments], commentlist => 57, optionalcomments => 59, comment => 2},
		{reduce => [5,  \&automakerule]}
);